package com.github.scausidc.chu.user.model;
// Generated 2015-5-7 17:46:37 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Admin generated by hbm2java
 */
public class Admin extends com.github.scausidc.chu.user.model.User implements java.io.Serializable {

    public Admin() {
    }

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        Admin c = (Admin)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }


}


