package com.github.scausidc.chu.user.model;
// Generated 2015-5-7 17:31:14 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

  // ENUM
    // 帐户状态枚举
    /** status = 0, 注册
     */
    public static final Byte STATUS_REGISTERED = 0;
    /** status = 1, 已验证邮箱
     */
    public static final Byte STATUS_ACTIVATED = 1;
    /** status = -1, 主动注销
     */
    public static final Byte STATUS_CANCELED = -1;
    /** status = -2, 封号
     */
    public static final Byte STATUS_BANNED = -2;

    /** id
     */
    protected Long id;
    /** 邮件地址(63), 唯一, 非空
     */
    protected String mail;
    /** 用户名(63), 唯一
     */
    protected String uname;
    /** 通信密钥(16)
     */
    protected byte[] secret;
    /** 盐(8)
     */
    protected byte[] salt;
    /** 登录密钥(16)
     */
    protected byte[] pass;
    /** 账户状态, 已弃用
     */
    protected Byte status;
    /** 注册时间
     */
    protected Date regDate;
    /** 类辨别符
     */
    protected String clazz;

    public User() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getUname() {
        return this.uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public byte[] getSecret() {
        return this.secret;
    }

    public void setSecret(byte[] secret) {
        this.secret = secret;
    }

    public byte[] getSalt() {
        return this.salt;
    }

    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

    public byte[] getPass() {
        return this.pass;
    }

    public void setPass(byte[] pass) {
        this.pass = pass;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Date getRegDate() {
        return this.regDate;
    }

    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    public String getClazz() {
        return this.clazz;
    }

    public void setClazz(String clazz) {
        this.clazz = clazz;
    }

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        User c = (User)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }


}


