package com.github.scausidc.chu.raffle.model;
// Generated 2015-5-13 14:46:05 by Hibernate Tools 4.0.0



/**
 * Awarded generated by hbm2java
 */
public class Awarded  implements java.io.Serializable {


    protected Long id;
    protected Long raffle;
    protected Integer award;
    protected byte[] passcode;
    protected Boolean redeemed;

    public Awarded() {
    }

    public Awarded(Long raffle, Integer award) {
       this.raffle = raffle;
       this.award = award;
       this.redeemed = false;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRaffle()
    {
        return(this.raffle);
    }

    public void setRaffle(Long raffle)
    {
        this.raffle = raffle;
    }

    public Long getAwarded() {
        return this.raffle;
    }

    public void setAwarded(Long raffle) {
        this.raffle = raffle;
    }
    public Integer getAward() {
        return this.award;
    }

    public void setAward(Integer award) {
        this.award = award;
    }
    public byte[] getPasscode() {
        return this.passcode;
    }

    public void setPasscode(byte[] passcode) {
        this.passcode = passcode;
    }
    public Boolean isRedeemed() {
        return this.redeemed;
    }

    public void setRedeemed(Boolean redeemed) {
        this.redeemed = redeemed;
    }

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        Awarded c = (Awarded)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }




}


