package com.github.scausidc.chu.raffle.model;
// Generated 2015-5-12 15:28:34 by Hibernate Tools 4.0.0



/**
 * Raffle generated by hbm2java
 */
public class Raffle  implements java.io.Serializable {


    protected Long id;
    protected String title;
    protected String metainfo;
    protected Boolean enabled;
    protected Boolean disableOnExhausted;
    protected Integer peerPending;
    protected Boolean fallbackEnabled;
    protected String[] awardName;
    protected String[] awardImage;
    protected Integer[] awardCapacity;
    protected Integer[] awardShewing;
    protected Integer[] awardSlicing;

    public Raffle() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    public String getMetainfo() {
        return this.metainfo;
    }

    public void setMetainfo(String metainfo) {
        this.metainfo = metainfo;
    }
    public Boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    public Boolean isDisableOnExhausted() {
        return this.disableOnExhausted;
    }

    public void setDisableOnExhausted(Boolean disableOnExhausted) {
        this.disableOnExhausted = disableOnExhausted;
    }
    public Integer getPeerPending() {
        return this.peerPending;
    }

    public void setPeerPending(Integer peerPending) {
        this.peerPending = peerPending;
    }
    public Boolean isFallbackEnabled() {
        return this.fallbackEnabled;
    }

    public void setFallbackEnabled(Boolean fallbackEnabled) {
        this.fallbackEnabled = fallbackEnabled;
    }
    public String[] getAwardName() {
        return this.awardName;
    }

    public void setAwardName(String[] awardName) {
        this.awardName = awardName;
    }
    public String[] getAwardImage() {
        return this.awardImage;
    }

    public void setAwardImage(String[] awardImage) {
        this.awardImage = awardImage;
    }
    public Integer[] getAwardCapacity() {
        return this.awardCapacity;
    }

    public void setAwardCapacity(Integer[] awardCapacity) {
        this.awardCapacity = awardCapacity;
    }
    public Integer[] getAwardShewing() {
        return this.awardShewing;
    }

    public void setAwardShewing(Integer[] awardShewing) {
        this.awardShewing = awardShewing;
    }
    public Integer[] getAwardSlicing() {
        return this.awardSlicing;
    }

    public void setAwardSlicing(Integer[] awardSlicing) {
        this.awardSlicing = awardSlicing;
    }

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        Raffle c = (Raffle)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }



}


